app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::resource('article', 'ArticlesController');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'articles';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'content',
        'user_id',
    ];

    public function author()
    {
        return $this->hasOne(User::class, 'id', 'user_id', 'users');
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getNameAttribute()
    {
        return $this->attributes['first_name'].' '.$this->attributes['last_name'];
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleCreateRequest;
use App\Models\Article;
use App\Models\User;
use Illuminate\Http\Request;

use App\Http\Requests;

class ArticlesController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('articles.index')
            ->with('articles', $articles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $authors = User::all();
        return view('articles.create')
            ->with('authors', $authors);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(ArticleCreateRequest $data)
    {
        $article = new Article();
        $article->title = $data->title;
        $article->content = $data->content_full;
        $article->user_id = $data->author_id;

        if($article->save()){
            $return_msg['message_msg'] = 'Article was save success.';
            $return_msg['message_type'] = 'success';
            $return_msg['message_closable'] = true;
        } else {
            $return_msg['message_msg'] = 'Save article give error.';
            $return_msg['message_type'] = 'warning';
            $return_msg['message_closable'] = false;
        }
        return redirect()->route('article.index')->with($return_msg);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $article = Article::find($id);
        return view('articles.show')
            ->with('article', $article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        $authors = User::all();
        return view('articles.edit')
            ->with('article', $article)
            ->with('authors', $authors);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(ArticleCreateRequest $data, $id)
    {
        $article = Article::find($id);
        if(!is_object($article)){
            $return_msg['message_msg'] = 'Article dont\'t find.';
            $return_msg['message_type'] = 'warning';
            $return_msg['message_closable'] = false;

            return redirect()->route('article.index')->with($return_msg);
        }

        $article->title = $data->title;
        $article->content = $data->content_full;
        $article->user_id = $data->author_id;

        $return_msg = array();

        if($article->save()){
            $return_msg['message_msg'] = 'Article was create success.';
            $return_msg['message_type'] = 'success';
            $return_msg['message_closable'] = true;
        } else {
            $return_msg['message_msg'] = 'Create article give error.';
            $return_msg['message_type'] = 'warning';
            $return_msg['message_closable'] = false;
        }
        return redirect()->route('article.index')->with($return_msg);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $return_msg = array();
        if(!is_object($article)){
            $return_msg['message_msg'] = 'Article dont\'t find.';
            $return_msg['message_type'] = 'warning';
            $return_msg['message_closable'] = false;

            return redirect()->route('article.index')->with($return_msg);
        }

        if($article->delete()){

            $return_msg['message_msg'] = 'Article is delete.';
            $return_msg['message_type'] = 'success';
            $return_msg['message_closable'] = false;
        }
        return redirect()->route('article.index')->with($return_msg);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Add Form Article
                    </div>

                    <div class="panel-body">
                        {!! Form::open(['route' => ['article.store'], 'method' => 'post', 'class' => 'form-horizontal']) !!}

                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Title</label>

                            <div class="col-md-6">
                                {!! Form::text('title', old('title'), array('class' => 'form-control')) !!}

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('content_full') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Full Text</label>

                            <div class="col-md-6">
                                {!! Form::textarea('content_full', old('content_full'), array('class' => 'form-control')) !!}

                                @if ($errors->has('content_full'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('content_full') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('author_id') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Author</label>

                            <div class="col-md-6">
                                {!! Form::select('author_id',['---'] + $authors->pluck('name', 'id')->toArray(), old('author_id'), array('class' => 'form-control')) !!}

                                @if ($errors->has('author_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('author_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-plus"></i> Add Article
                                </button>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Form Article
                    </div>

                    <div class="panel-body">
                        {!! Form::open(['route' => ['article.update', $article->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}

                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Title</label>

                            <div class="col-md-6">
                                {!! Form::text('title', $article->title, array('class' => 'form-control')) !!}

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('content_full') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Full Text</label>

                            <div class="col-md-6">
                                {!! Form::textarea('content_full', $article->content, array('class' => 'form-control')) !!}

                                @if ($errors->has('content_full'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('content_full') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('author_id') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Full Text</label>

                            <div class="col-md-6">
                                {!! Form::select('author_id', $authors->pluck('name', 'id'), $article->author_id, array('class' => 'form-control')) !!}

                                @if ($errors->has('content'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('content') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-plus"></i> Edit Article
                                </button>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Article List
                        <a href="{{ route('article.create') }}" class="btn btn-default btn-xs pull-right">New</a>
                    </div>

                    <div class="panel-body">
                        @include('message')
                        <table class="table tab-content">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Title</th>
                                    <th>Content Short</th>
                                    <th>Author</th>
                                    <th>Create</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($articles as $article)
                                <tr>
                                    <td>{{ $article->id }}</td>
                                    <td>{{ $article->title }}</td>
                                    <td>{{ substr($article->content, 1, 30) }}</td>
                                    <td>{{ $article->author->name }}</td>
                                    <td>{{ $article->created_at }}</td>
                                    <td>
                                        {!! Form::open(['route' => ['article.destroy', $article->id], 'method' => 'delete', 'class' => 'form-horizontal']) !!}
                                        <div class="btn-group-sm">
                                            <a href="{{ route('article.show',$article->id) }}" class="btn btn-primary">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a href="{{ route('article.edit',  $article->id) }}" class="btn btn-info" >
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a href="javascript:;" onclick="$(this).closest('form').submit()"  class="btn btn-danger">
                                                <i class="fa fa-times"></i>
                                            </a>
                                        </div>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                                @empty
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">
                        {{ $article->title }}
                    </div>

                    <div class="panel-body">
                        {{ $article->content }}
                    </div>
                    <div class="panel-footer">
                        Author: {{ $article->author->name }}
                        <span class="pull-right">
                            Created: {{ $article->created_at }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li><a href="{{ route('article.index') }}">Articles</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/message.blade.php
@if (Session::has('message_msg') && (Session::get('message_type')) != null)
<div class="alert alert-{!! Session::get('message_type') !!} alert-dismissable" style="margin-top: 15px;">
    @if (Session::has('message_closable') && Session::get('message_closable') == true)
        <div class="col-md-1 pull-right">
            <a type="button" class="close" data-dismiss="alert" aria-hidden="true"><i class="fa fa-times"></i></a>
        </div>
    @endif
    <h4>
        @if(Session::get('message_type') == 'error' || Session::get('message_type') == 'danger')
            <i class="fa fa-exclamation-triangle"></i>
        @elseif(Session::get('message_type') == 'warning')
            <i class="fa fa-warning"></i>
        @elseif(Session::get('message_type') == 'info')
            <i class="fa fa-info"></i>
        @elseif(Session::get('message_type') == 'success')
            <i class="fa fa-check"></i>
        @endif
            @if(Session::get('message_type') == 'success')
                Succes
            @elseif(Session::get('message_type') == 'danger')
                Let op
            @else
                {!! ucfirst(Session::get('message_type')) !!}
            @endif
    </h4>
    <p>
        {!! Session::get('message_msg') !!}
    </p>
</div>
<div class="clearfix"></div>
@endif